name: Clone Workflow

on:
  workflow_dispatch:

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: main
        ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Copy files to TerpConnect
      uses: appleboy/scp-action@master
      with:
        host: terpconnect.umd.edu
        username: ${{ secrets.TERPCONNECT_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./
        target: /afs/terpconnect.umd.edu/users/d/i/ayedla1/public_html/webtemplate
